language: node_js
node_js:
  - '4.3.0'
before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install -g bower gulp'
  - 'npm install' # install npm packages
  - 'bower install' # install bower packages

after_script:
  # - 'gulp' # or other command for build, run tests, etc
