language: node_js
node_js:
  - '6.4.0'
before_script:
  - 'npm install -g webpack'
  - 'npm install' # install npm packages

after_script:
  - 'NODE_ENV=production && webpack -p --config ./webpack.prod.config.js' # or other command for build, run tests, etc
